- name: Créer le répertoire de monitoring
  ansible.builtin.file:
    path: "{{ monitoring_dir }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0755'
  become: true

- name: Copier docker-compose-monitoring.yml
  ansible.builtin.template:
    src: docker-compose-monitoring.yml.j2
    dest: "{{ monitoring_dir }}/docker-compose.yml"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0644'
  become: true

- name: Copier prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_dir }}/prometheus.yml"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0644'
  become: true

- name: Déployer Prometheus et Grafana via docker_compose
  become: true
  become_user: "{{ docker_user }}"
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_dir }}"
    files:
      - docker-compose.yml
    state: present
    docker_cli: "/home/{{ docker_user }}/bin/docker"
    docker_host: "unix:///run/user/{{ admin_db_uid.stdout }}/docker.sock"
  when: inventory_hostname == 'vm1'