- name: Configurer Netdata pour lire les logs Laravel
  ansible.builtin.copy:
    dest: "/home/admin_db/netdata-config/go.d/web_log.conf"
    owner: admin_db
    group: admin_db
    mode: '0644'
    content: |
      jobs:
        - name: laravel
          path: /var/log/laravel/laravel.log
          log_type: json
          update_every: 1
  become: yes
  when: inventory_hostname == 'vm1'