networks:
  app_network:
    name: app_network
    driver: bridge

services:
  traefik:
    build: ../traefik
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--configFile=/traefik.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=app_network"
      - "--entrypoints.web.address=:8088"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.monitoring.address=:3000"
    ports:
      - "8088:8088"
      - "8443:8443"
      - "3000:3000"
      - "8080:8080"
    volumes:
      - "${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro"
      - "/home/admin_db/traefik/files:/etc/traefik"
    networks:
      - app_network

  app:
    # set container name app
    container_name: app
    restart: unless-stopped
    stdin_open: false
    tty: false
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_DEBUG: "true"
      APP_ENV: "dev"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_database
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.app.rule=Host(`${APP_HOST:-192.168.56.11}`)"
      - "traefik.http.routers.app.entrypoints=web" 
      # HTTPS
      - "traefik.http.routers.app-secure.rule=Host(`${APP_HOST:-192.168.56.11}`)"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=80"
    networks:
      - app_network
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_database}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-app_root_password}
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # Permet d'exécuter des scripts SQL initiaux
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - app_network

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE # нужно для некоторых плагинов Netdata
      - SYS_ADMIN # для сбора статистики c контейнеров
    security_opt:
      - apparmor:unconfined
    volumes:
      - "${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro"
      - /home/admin_db/app/storage/logs:/var/log/laravel:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring.rule=Host(`${APP_HOST:-192.168.56.11}`)"
      - "traefik.http.routers.monitoring.entrypoints=monitoring"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
    networks:
      - app_network

volumes:
  db_data:
