services:
  postgres-master:
    image: postgres:15
    container_name: pg_master
    environment:
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_database
    ports:
      - "5432:5432"
    volumes:
      - pg_master_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_db"]
      interval: 5s
      retries: 5
volumes:
  pg_master_data:
