- name: Activer CRB
  ansible.builtin.command: dnf config-manager --set-enabled crb
  become: true

- name: Rafraîchir le cache DNF
  ansible.builtin.dnf:
    update_cache: yes
  become: true

- name: Vérifier que CRB est bien activé
  ansible.builtin.shell: dnf repolist enabled | grep -i crb
  register: crb_check
  ignore_errors: true
  changed_when: false

- name: Afficher l’état de CRB
  ansible.builtin.debug:
    var: crb_check.stdout_lines
