- name: Automatisation configuration mysql dans la vm
  hosts: vms
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: user
    - role: config
    - role: konstruktoid.docker_rootless
      vars:
        docker_user_bashrc: true
    - role: traefik
    - role: setup_app
    - role: backup
    # - role: monitoring
