- name: Automatisation configuration mysql dans la vm
  hosts: vms
  become: true
  
  roles:
    - role: user
    - role: konstruktoid.docker_rootless
    - role: setup_app # Mettre en place la vm avec l'app et la db
    #Â - role: backup
    # - role: monitoring
