- name: Automatisation configuration mysql dans la vm
  hosts: vms
  become: true
  
  roles:
    - role: user
    - role: konstruktoid.docker_rootless
    - role: setup_db # Mettre en place la vm master et replica
    # - role: pgbounce # Mettre en place le load balancer
    # - role: monitoring
