- name: Automatisation configuration mysql dans la vm
  hosts: vms
  become: true
  
  roles:
    - role: user
    - role: konstruktoid.docker_rootless
      vars:
        docker_user_bashrc: true
    - role: setup_app
    #- role: traefik
    - role: backup
    - role: monitoring
